### ISSUE TITLE
RaRe ranking

### ISSUE THREAD

**Issue by pascalhuszar** [afshinrahimi/mmner#1]
> first pretrain on top k (here 10) annotations (sorted by f1 results in taglangtag.json) and then fine-tune on lowres gold data from the target language.

Is this taglangtag.json missing? I would like to see the ranking for the languages, especially for the Germanic language family

**Comment by afshinrahimi** [comment]
Hi Pascal,
Figure 5 (in the Appendix) shows taglangtag.json.
If you need the json file I'll be able to upload it on Monday.

**Comment by pascalhuszar** [comment]
no need to, now i know :)
